import { Glob } from "bun";
import { join } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

const CACHE_FOLDER = join(process.cwd(), "node_modules", ".satone");
const ROUTES_PATH = join(process.cwd(), "src", "routes");
const GLOB = new Glob("**/*.ts[x]");

const BANNER =
  `
//! THIS FILE IS AUTOMATICALLY GENERATED BY "satone" CLI
//! DURING "build" AND "dev" COMMANDS.
`.trim() + "\n\n";

const checkCacheFolder = async () => {
  await mkdir(CACHE_FOLDER, { recursive: true });
};

const write = async (file: string, content: string) => {
  await writeFile(join(CACHE_FOLDER, file), content, "utf8");
};

/**
 * Will distribute the types under `node_modules/.satone/eden.d.ts`
 */
const generateEdenTypes = async () => {
  await checkCacheFolder();

  let output = BANNER + `import Elysia from "elysia";\n\n`;
  const routes: string[] = [];

  for await (const file of GLOB.scan(ROUTES_PATH)) {
    const imports = await import(join(ROUTES_PATH, file));
    if (!imports.server) continue;

    const route = "/" + file.replace("index", "").replace(/\.ts[x]/, "");

    output += `import { server as plug${routes.length} } from ${JSON.stringify(
      join("..", "..", "src", "routes", file)
    )};\n`;

    routes.push(route);
  }

  output += `\nconst app = new Elysia()`;
  for (let curr = 0; curr < routes.length; curr++) {
    const route = routes[curr];
    output += `\n  .group(${JSON.stringify(
      route
    )}, (app) => app.use(plug${curr}))`;
  }

  output += `;\n\nexport type App = typeof app;\n`;
  await write("eden.ts", output);
};

const generateIndexDTS = async () => {
  await checkCacheFolder();

  let output = BANNER + `import type { App } from "./eden";\n\n`;

  output +=
    `
declare global {
  export type SatoneServerRoutes = App;
}
  `.trim() + "\n";

  await write("index.d.ts", output);
};

export const generateTypes = async () => {
  await generateIndexDTS();
  await generateEdenTypes();
};
