import type { VoidComponent } from "solid-js";

// @ts-expect-error : will be generated by `vite-plugin-pages`
import routes from "~solid-pages";

export const FileRoutes: VoidComponent = () => {
  return routes;
};
